gen-x: https://docs.google.com/spreadsheets/d/1gSflglwFiLXCpzflf8_2C6-DalZGI1AVRXfytZZtAYA/edit?pli=1#gid=218432404

gen-y:https://docs.google.com/spreadsheets/d/1yNKQnFO1uK3PjDEBAeiGGp54Q3i0GGozjTn3sMe6vzw/edit#gid=727754713

gen-z:https://docs.google.com/spreadsheets/d/15Ikgky3vorCWCetYTEZr0vhoxbzV7Oc9ZbcywlWYpYc/edit#gid=567397654

Sheet : Form Responses 1

## genX

In [161]:
import pandas as pd
sheet_id = "1gSflglwFiLXCpzflf8_2C6-DalZGI1AVRXfytZZtAYA"
sheet_name = "p_anax"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
genx = pd.read_csv(url, low_memory=False)
# df_main = df_main[df_main.tahun==2021]
genx = genx.iloc[:,1:77]

In [162]:
coln = genx.iloc[:,70:77]
coln.columns

Index(['What is your age?', 'Gender', 'Employment Status', 'Employment Sector',
       'Education Level', 'Monthly Income'],
      dtype='object')

In [163]:
genx.iloc[:,70:77]

,What is your age?,Gender,Employment Status,Employment Sector,Education Level,Monthly Income
0,29-35 years old,Female,Full-time,Government-sector based,Bachelor Degree,"Below RM3,440"
1,45-59 years old,Female,Full-time,Government-sector based,Master,"RM3,440 - RM5,249"
2,29-35 years old,Female,Full-time,Private-sector based,Bachelor Degree,"RM3,440 - RM5,249"
3,45-59 years old,Male,Others,Self-employed,Secondary School,"RM3,440 - RM5,249"
4,45-59 years old,Male,Full-time,Government-sector based,Matriculation/Diploma,"RM3,440 - RM5,249"
...,...,...,...,...,...,...
64,45-59 years old,Male,Part-time,Private-sector based,Bachelor Degree,"RM3,440 - RM5,249"
65,45-59 years old,Female,Full-time,Government-sector based,Master,"RM3,440 - RM5,249"
66,45-59 years old,Male,Full-time,Government-sector based,PhD,"RM7,790 - RM11,819"
67,45-59 years old,Female,Contract,Government-sector based,Master,"RM3,440 - RM5,249"
68,45-59 years old,Male,Full-time,Government-sector based,Matriculation/Diploma,"RM3,440 - RM5,249"

In [164]:
# Encode categorical variables using one-hot encoding
encoded_data = pd.get_dummies(genx)

# Calculate the correlation matrix for all columns
corr_matrix = encoded_data.corr()

# Select the correlation values for the last 7 columns
last_7_corr = corr_matrix.iloc[-7:, :]

# Display the correlation values for the last 7 columns
# print(last_7_corr)

# # List the column names with the highest correlation for each column
highest_corr_columns = last_7_corr.idxmax()

# # Print the column names with the highest correlation
highest_corr_columns

# Create a DataFrame to display the pairs with the highest correlation
df_highest_corr_pairs = pd.DataFrame(highest_corr_pairs, columns=['Correlation'])

# Print the DataFrame
df_highest_corr_pairs

                                                                                     Correlation
Education Level_Secondary School Employment Sector_Self-employed                        0.648306
Monthly Income_Above RM11,819     [[EWB15] In most ways my life is close to idea...     0.550482
                                  [[EWB11] I am encouraged to develop new skills...     0.517863
                                  [[EWB12] I am involved in decisions that affec...     0.517863
                                  [[EWB23] I am involved in decisions that affec...     0.517863

generate synthetic data for genx

In [165]:
genx.iloc[:, 1].unique()

array(['Agree', 'Neutral', 'Strongly Agree', 'Strong Disagree',
       'Disagree'], dtype=object)

In [166]:
# Assuming you have a DataFrame called genx
# genx = pd.DataFrame(...)

# Define the mapping dictionary
mapping = {
    'Strongly Agree': 5,
    'Agree': 4,
    'Neutral': 3,
    'Disagree': 2,
    'Strong Disagree': 1
}

# Iterate over each column from index 1 to 69 and apply the mapping
for column_index in range(0, 70):
    genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)

C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\749817812.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genx.iloc[:, column_index] = genx.iloc[:, column_index].map(mapping)

In [167]:
forsdata = genx.iloc[:, [i for i in range(0, len(genx.columns)) if i not in [70,71,72]]]
forsdata.head(15) # only include 'Employment Sector', 'Education Level', 'Monthly Income'

,[[EWB1] I have a clear set of goals and aims to enable me to do my job],[[EWB2] I feel able to voice opinions and influence changes in my area of work],[[EWB3] I have the opportunity to use my abilities at work],[[EWB4] I feel well at the moment],[[EWB5] My employer provides adequate facilities and flexibility for me to fit work in around my family life],[[EWB6] My current working hours / patterns suit my personal circumstances],[[EWB7] I often feel under pressure at work],[[EWB8] When I have done a good job it is acknowledged by my line manager],"[[EWB9] Recently, I have been feeling unhappy and depressed]",[[EWB10] I am satisfied with my life],...,[[OP8] Usually in this organization there is flexibility to work flexible hours],[[OP9] The organization provides facility of job sharing to the employees],[[OP10] Organization adopts employment programs that help in achieving work-life balance],[[OP11] Employees are permitted enough discretion in doing their work],[[OP12] Employees are encouraged to raise their voice when they disagree over a decision],[[OP13] The organization provides enough opportunity to employees for providing inputs on a wide range of issues],[[OP14] Employees are involved in decision making with regard to recruitment and selection of a new colleague],Employment Sector,Education Level,Monthly Income
0,4,4,4,4,4,4,4,4,3,3,...,4.0,4.0,4.0,4.0,2.0,4.0,3.0,Government-sector based,Bachelor Degree,"Below RM3,440"
1,4,4,4,4,2,4,2,4,2,4,...,4.0,3.0,3.0,4.0,4.0,4.0,3.0,Government-sector based,Master,"RM3,440 - RM5,249"
2,4,3,4,2,4,4,4,4,4,4,...,4.0,4.0,4.0,2.0,4.0,4.0,3.0,Private-sector based,Bachelor Degree,"RM3,440 - RM5,249"
3,4,4,4,4,4,4,4,4,4,4,...,4.0,4.0,3.0,4.0,4.0,3.0,4.0,Self-employed,Secondary School,"RM3,440 - RM5,249"
4,4,3,4,3,3,4,2,2,2,2,...,3.0,2.0,2.0,2.0,NaN,NaN,NaN,Government-sector based,Matriculation/Diploma,"RM3,440 - RM5,249"
5,5,5,5,4,5,5,1,5,1,4,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,Private-sector based,Bachelor Degree,"RM7,790 - RM11,819"
6,3,3,3,3,3,3,3,3,3,3,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,Government-sector based,Matriculation/Diploma,"RM3,440 - RM5,249"
7,4,4,4,4,4,4,3,4,3,4,...,NaN,4.0,2.0,NaN,NaN,2.0,NaN,Private-sector based,Master,"RM5,250 - RM7,689"
8,4,4,4,5,4,5,3,3,3,3,...,4.0,NaN,4.0,4.0,4.0,3.0,3.0,Private-sector based,Master,"RM5,250 - RM7,689"
9,4,4,4,4,4,4,4,4,2,4,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,Self-employed,Secondary School,"RM3,440 - RM5,249"
10,5,4,5,5,5,5,3,4,2,5,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,Private-sector based,Master,"Above RM11,819"
11,4,4,4,4,4,4,4,4,3,4,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,Self-employed,Secondary School,"RM3,440 - RM5,249"
12,5,4,5,3,4,4,3,5,4,3,...,5.0,4.0,4.0,3.0,4.0,4.0,5.0,Private-sector based,Bachelor Degree,"Below RM3,440"
13,4,4,4,4,4,4,2,5,1,4,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,Private-sector based,Matriculation/Diploma,"Below RM3,440"
14,4,4,3,2,4,3,3,2,3,4,...,4.0,3.0,3.0,3.0,3.0,3.0,2.0,Government-sector based,Bachelor Degree,"RM7,790 - RM11,819"

Consistency Questionable??

In [168]:
# Calculate the maximum value by row
forsdata['max_value'] = forsdata.max(axis=1)

# Calculate the minimum value by row
forsdata['min_value'] = forsdata.min(axis=1)

forsdata['consistency'] = forsdata['max_value']/forsdata['min_value']

C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\3523466586.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  forsdata['max_value'] = forsdata.max(axis=1)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\3523466586.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forsdata['max_value'] = forsdata.max(axis=1)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\3523466586.py:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  forsdata['min_value'] = forsdata.min(axis=1)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\3523466586.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forsdata['min_value'] = forsdata.min(axis=1)

In [169]:
forsdata[forsdata['consistency']==1]

,[[EWB1] I have a clear set of goals and aims to enable me to do my job],[[EWB2] I feel able to voice opinions and influence changes in my area of work],[[EWB3] I have the opportunity to use my abilities at work],[[EWB4] I feel well at the moment],[[EWB5] My employer provides adequate facilities and flexibility for me to fit work in around my family life],[[EWB6] My current working hours / patterns suit my personal circumstances],[[EWB7] I often feel under pressure at work],[[EWB8] When I have done a good job it is acknowledged by my line manager],"[[EWB9] Recently, I have been feeling unhappy and depressed]",[[EWB10] I am satisfied with my life],...,[[OP11] Employees are permitted enough discretion in doing their work],[[OP12] Employees are encouraged to raise their voice when they disagree over a decision],[[OP13] The organization provides enough opportunity to employees for providing inputs on a wide range of issues],[[OP14] Employees are involved in decision making with regard to recruitment and selection of a new colleague],Employment Sector,Education Level,Monthly Income,max_value,min_value,consistency
6,3,3,3,3,3,3,3,3,3,3,...,3.0,3.0,3.0,3.0,Government-sector based,Matriculation/Diploma,"RM3,440 - RM5,249",3.0,3.0,1.0
23,5,5,5,5,5,5,5,5,5,5,...,5.0,5.0,5.0,5.0,Private-sector based,Master,"RM3,440 - RM5,249",5.0,5.0,1.0
59,1,1,1,1,1,1,1,1,1,1,...,NaN,NaN,NaN,NaN,Others,Master,"RM5,250 - RM7,689",1.0,1.0,1.0

In [170]:
# !pip install fancyimpute

In [171]:
import random
import pandas as pd
from fancyimpute import IterativeImputer

# Assuming you have already loaded your dataframe 'genx'

# Select relevant columns
# forsdata = genx.iloc[:, [i for i in range(0, len(genx.columns)) if i in [70, 71, 72]]]

# Randomly select values for 'Employment Sector', 'Education Level', and 'Monthly Income'
sector = random.choice(forsdata['Employment Sector'].unique())
education = random.choice(forsdata['Education Level'].unique())
income = random.choice(forsdata['Monthly Income'].unique())

# Fill the selected values in the dataframe
forsdata.loc[forsdata['Employment Sector'].isnull(), 'Employment Sector'] = sector
forsdata.loc[forsdata['Education Level'].isnull(), 'Education Level'] = education
forsdata.loc[forsdata['Monthly Income'].isnull(), 'Monthly Income'] = income

# Now, let's use MICE to impute missing values in other columns
exclude_columns = ['Employment Sector', 'Education Level', 'Monthly Income']

# Specify columns to impute
columns_to_impute = [col for col in forsdata.columns if col not in exclude_columns]

# Create imputer 
imputer = IterativeImputer()

# Fit and transform to impute 
forsdata_imputed = pd.DataFrame(imputer.fit_transform(forsdata[columns_to_impute]), 
                               columns=columns_to_impute)  

# Replace imputed values
forsdata[columns_to_impute] = forsdata_imputed[columns_to_impute]

# Generate 200 synthetic data points
synthetic_data = pd.DataFrame(columns=forsdata.columns)
for _ in range(200):
    synthetic_row = forsdata.iloc[random.randint(0, len(forsdata) - 1)]
    synthetic_data = synthetic_data.append(synthetic_row, ignore_index=True)

# Convert numeric columns to integers
synthetic_data[columns_to_impute] = synthetic_data[columns_to_impute].astype(int)

# Display the synthetic data
synthetic_data

C:\Users\najmi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\impute\_iterative.py:785: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2160965614.py:40: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  synthetic_data = synthetic_data.append(synthetic_row, ignore_index=True)

,[[EWB1] I have a clear set of goals and aims to enable me to do my job],[[EWB2] I feel able to voice opinions and influence changes in my area of work],[[EWB3] I have the opportunity to use my abilities at work],[[EWB4] I feel well at the moment],[[EWB5] My employer provides adequate facilities and flexibility for me to fit work in around my family life],[[EWB6] My current working hours / patterns suit my personal circumstances],[[EWB7] I often feel under pressure at work],[[EWB8] When I have done a good job it is acknowledged by my line manager],"[[EWB9] Recently, I have been feeling unhappy and depressed]",[[EWB10] I am satisfied with my life],...,[[OP11] Employees are permitted enough discretion in doing their work],[[OP12] Employees are encouraged to raise their voice when they disagree over a decision],[[OP13] The organization provides enough opportunity to employees for providing inputs on a wide range of issues],[[OP14] Employees are involved in decision making with regard to recruitment and selection of a new colleague],Employment Sector,Education Level,Monthly Income,max_value,min_value,consistency
0,1,1,1,3,2,2,3,1,3,3,...,3,3,3,3,Private-sector based,Bachelor Degree,"RM5,250 - RM7,689",3,1,3
1,4,4,4,4,5,5,3,4,2,4,...,4,4,4,4,Government-sector based,Bachelor Degree,"RM3,440 - RM5,249",5,2,2
2,4,4,4,3,3,4,2,3,2,2,...,4,4,4,3,Government-sector based,Matriculation/Diploma,"RM3,440 - RM5,249",5,1,5
3,5,5,5,5,5,5,2,5,2,5,...,3,3,4,3,Government-sector based,Bachelor Degree,"RM5,250 - RM7,689",5,2,2
4,4,4,4,5,4,5,3,3,3,3,...,4,4,3,3,Private-sector based,Master,"RM5,250 - RM7,689",5,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,Government-sector based,Master,"RM5,250 - RM7,689",5,4,1
196,4,4,4,4,4,4,3,4,1,3,...,4,4,4,4,Government-sector based,Bachelor Degree,"RM7,790 - RM11,819",5,1,5
197,4,5,4,3,4,4,3,4,3,3,...,3,4,4,2,Private-sector based,Bachelor Degree,"RM7,790 - RM11,819",5,2,2
198,5,4,4,4,4,3,2,4,2,4,...,4,2,3,2,Government-sector based,PhD,"RM7,790 - RM11,819",5,2,2
199,4,3,3,4,4,4,2,3,2,4,...,4,4,4,4,Government-sector based,Bachelor Degree,"RM3,440 - RM5,249",5,2,2

In [172]:
synthetic_data.to_csv('synthetic_data_genX.csv', index=False)

In [173]:
synthetic_data.to_clipboard(index=False)

## genY

In [12]:
import pandas as pd
sheet_id = "1yNKQnFO1uK3PjDEBAeiGGp54Q3i0GGozjTn3sMe6vzw"
sheet_name = "p_anay"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
geny = pd.read_csv(url, low_memory=False)
# df_main = df_main[df_main.tahun==2021]
geny

,Timestamp,[[EWB1] I have a clear set of goals and aims to enable me to do my job],[[EWB2] I feel able to voice opinions and influence changes in my area of work],[[EWB3] I have the opportunity to use my abilities at work],[[EWB4] I feel well at the moment],[[EWB5] My employer provides adequate facilities and flexibility for me to fit work in around my family life],[[EWB6] My current working hours / patterns suit my personal circumstances],[[EWB7] I often feel under pressure at work],[[EWB8] When I have done a good job it is acknowledged by my line manager],"[[EWB9] Recently, I have been feeling unhappy and depressed]",...,Employment Sector,Education Level,Monthly Income,Email/Phone Number,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83
0,1/15/2024 14:58:20,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Neutral,...,Government-sector based,Bachelor Degree,"Below RM3,440",0134866186,NaN,done 11/2/2024,NaN,NaN,NaN,NaN
1,1/16/2024 9:40:33,Agree,Neutral,Agree,Disagree,Agree,Agree,Agree,Agree,Agree,...,Private-sector based,Bachelor Degree,"RM3,440 - RM5,249",0122594393,NaN,done 11/2/2024,NaN,NaN,NaN,NaN
2,1/24/2024 14:26:11,Agree,Agree,Agree,Agree,Agree,Agree,Neutral,Agree,Neutral,...,Private-sector based,Master,"RM5,250 - RM7,689",shamshillahkamarzaman@gmail.com,NaN,done reedem 9/2/2024 di gen x section in tng file,NaN,NaN,NaN,NaN
3,1/15/2024 14:16:04,Agree,Neutral,Agree,Neutral,Agree,Agree,Agree,Neutral,Neutral,...,Government-sector based,Master,"RM3,440 - RM5,249",0134748674,NaN,done 9/2/2024,NaN,NaN,NaN,NaN
4,1/15/2024 14:51:31,Agree,Strongly Agree,Strongly Agree,Strongly Agree,Agree,Agree,Strongly Agree,Agree,Neutral,...,Government-sector based,Master,"RM5,250 - RM7,689",0132705370,NaN,done 11/2/2024,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,2/13/2024 9:41:53,Agree,Neutral,Agree,Agree,Agree,Agree,Neutral,Neutral,Strong Disagree,...,Government-sector based,Matriculation/Diploma,"Below RM3,440",0193954339,NaN,done 15/2/2024,NaN,NaN,NaN,NaN
152,2/13/2024 14:55:45,Agree,Agree,Neutral,Neutral,Agree,Neutral,Neutral,Agree,Agree,...,Self-employed,PhD,"RM5,250 - RM7,689",drchefoney@gmail.com,NaN,done 16/2/2024,NaN,NaN,NaN,NaN
153,2/13/2024 9:53:13,Agree,Agree,Neutral,Agree,Agree,Strongly Agree,Agree,Neutral,Agree,...,Government-sector based,Matriculation/Diploma,"RM3,440 - RM5,249",langkopai5389@gmail.com,NaN,done 16/2/2024,NaN,NaN,NaN,NaN
154,2/13/2024 16:13:06,Agree,Agree,Agree,Agree,Agree,Agree,Neutral,Neutral,Neutral,...,Private-sector based,Bachelor Degree,"RM7,790 - RM11,819",0199511365,NaN,done 16/2/2024,NaN,NaN,NaN,NaN
155,2/14/2024 10:24:41,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Agree,Strongly Agree,Strong Disagree,Agree,Strong Disagree,...,Government-sector based,Bachelor Degree,"Below RM3,440",zulfadhlie96@gmail.com,NaN,done 16/2/2024,NaN,NaN,NaN,NaN

## genZ

In [174]:
import pandas as pd
sheet_id = "15Ikgky3vorCWCetYTEZr0vhoxbzV7Oc9ZbcywlWYpYc"
sheet_name = "p_anaz"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
genz = pd.read_csv(url, low_memory=False)
# df_main = df_main[df_main.tahun==2021]
genz = genz.iloc[:,1:77]

In [175]:
# Encode categorical variables using one-hot encoding
encoded_data = pd.get_dummies(genz)

# Calculate the correlation matrix for all columns
corr_matrix = encoded_data.corr()

# Select the correlation values for the last 7 columns
last_7_corr = corr_matrix.iloc[-7:, :]

# Display the correlation values for the last 7 columns
# print(last_7_corr)

# # List the column names with the highest correlation for each column
highest_corr_columns = last_7_corr.idxmax()

# # Print the column names with the highest correlation
highest_corr_columns

# Create a DataFrame to display the pairs with the highest correlation
df_highest_corr_pairs = pd.DataFrame(highest_corr_pairs, columns=['Correlation'])

# Print the DataFrame
df_highest_corr_pairs

                                                                                     Correlation
Education Level_Secondary School Employment Sector_Self-employed                        0.648306
Monthly Income_Above RM11,819     [[EWB15] In most ways my life is close to idea...     0.550482
                                  [[EWB11] I am encouraged to develop new skills...     0.517863
                                  [[EWB12] I am involved in decisions that affec...     0.517863
                                  [[EWB23] I am involved in decisions that affec...     0.517863

generate synthetic data for genx

In [176]:
genz.iloc[:, 1].unique()

array(['Strongly Agree', 'Agree', 'Neutral', 'Disagree',
       'Strong Disagree'], dtype=object)

In [177]:
# Assuming you have a DataFrame called genx
# genx = pd.DataFrame(...)

# Define the mapping dictionary
mapping = {
    'Strongly Agree': 5,
    'Agree': 4,
    'Neutral': 3,
    'Disagree': 2,
    'Strong Disagree': 1
}

# Iterate over each column from index 1 to 69 and apply the mapping
for column_index in range(0, 70):
    genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)

C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\2597130899.py:15: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  genz.iloc[:, column_index] = genz.iloc[:, column_index].map(mapping)

In [178]:
forsdata = genz.iloc[:, [i for i in range(0, len(genz.columns)) if i not in [70,71,72]]]
forsdata.head(15) # only include 'Employment Sector', 'Education Level', 'Monthly Income'

,[[EWB1] I have a clear set of goals and aims to enable me to do my job],[[EWB2] I feel able to voice opinions and influence changes in my area of work],[[EWB3] I have the opportunity to use my abilities at work],[[EWB4] I feel well at the moment],[[EWB5] My employer provides adequate facilities and flexibility for me to fit work in around my family life],[[EWB6] My current working hours / patterns suit my personal circumstances],[[EWB7] I often feel under pressure at work],[[EWB8] When I have done a good job it is acknowledged by my line manager],"[[EWB9] Recently, I have been feeling unhappy and depressed]",[[EWB10] I am satisfied with my life],...,[[OP8] Usually in this organization there is flexibility to work flexible hours],[[OP9] The organization provides facility of job sharing to the employees],[[OP10] Organization adopts employment programs that help in achieving work-life balance],[[OP11] Employees are permitted enough discretion in doing their work],[[OP12] Employees are encouraged to raise their voice when they disagree over a decision],[[OP13] The organization provides enough opportunity to employees for providing inputs on a wide range of issues],[[OP14] Employees are involved in decision making with regard to recruitment and selection of a new colleague],Employment Sector,Education Level,Monthly Income
0,2,5,5,5,3.0,5,2,5,5,5,...,3.0,2.0,5.0,2,3.0,3.0,3.0,Self-employed,Matriculation/Diploma,"Above RM11,819"
1,4,4,4,3,2.0,2,4,2,4,2,...,2.0,3.0,2.0,3,3.0,4.0,NaN,Government-sector based,Bachelor Degree,"Below RM3,440"
2,5,5,5,5,5.0,5,5,5,5,4,...,4.0,4.0,4.0,5,4.0,5.0,4.0,Government-sector based,Master,"Below RM3,440"
3,5,5,5,2,3.0,5,3,4,5,1,...,NaN,3.0,3.0,2,3.0,3.0,2.0,Government-sector based,Bachelor Degree,"RM3,440 - RM5,249"
4,4,4,4,4,4.0,2,4,3,3,4,...,4.0,4.0,4.0,4,4.0,4.0,4.0,Private-sector based,Bachelor Degree,"RM5,250 - RM7,689"
5,4,4,4,4,4.0,4,4,4,4,4,...,4.0,4.0,4.0,4,4.0,4.0,4.0,Private-sector based,Bachelor Degree,"Above RM11,819"
6,4,4,4,4,4.0,4,4,4,4,4,...,4.0,4.0,4.0,4,4.0,4.0,4.0,Private-sector based,Bachelor Degree,"Above RM11,819"
7,4,4,4,4,4.0,4,4,4,4,4,...,4.0,4.0,4.0,4,4.0,4.0,4.0,Private-sector based,Secondary School,"Above RM11,819"
8,4,3,4,4,3.0,4,3,3,2,4,...,4.0,3.0,3.0,3,2.0,3.0,4.0,Government-sector based,Master,"RM3,440 - RM5,249"
9,5,4,4,3,4.0,3,4,3,4,4,...,4.0,4.0,3.0,3,4.0,5.0,5.0,Private-sector based,Bachelor Degree,"Below RM3,440"
10,2,2,2,2,2.0,2,2,2,2,2,...,4.0,5.0,5.0,5,4.0,4.0,5.0,Government-sector based,Bachelor Degree,"RM3,440 - RM5,249"
11,4,3,4,4,5.0,4,5,4,4,4,...,3.0,4.0,3.0,4,3.0,4.0,3.0,Private-sector based,Bachelor Degree,"Below RM3,440"
12,5,3,3,4,5.0,5,1,4,2,3,...,3.0,5.0,4.0,2,3.0,3.0,NaN,Private-sector based,Bachelor Degree,"RM5,250 - RM7,689"
13,5,5,5,5,3.0,5,5,4,5,3,...,4.0,4.0,4.0,5,4.0,3.0,3.0,Private-sector based,Master,"Below RM3,440"
14,4,4,5,2,2.0,4,3,4,4,4,...,3.0,2.0,3.0,4,NaN,3.0,3.0,Private-sector based,Bachelor Degree,"RM3,440 - RM5,249"

Consistency Questionable??

In [179]:
# Calculate the maximum value by row
forsdata['max_value'] = forsdata.max(axis=1)

# Calculate the minimum value by row
forsdata['min_value'] = forsdata.min(axis=1)

forsdata['consistency'] = forsdata['max_value']/forsdata['min_value']

C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\3523466586.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  forsdata['max_value'] = forsdata.max(axis=1)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\3523466586.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forsdata['max_value'] = forsdata.max(axis=1)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\3523466586.py:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  forsdata['min_value'] = forsdata.min(axis=1)
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\3523466586.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  forsdata['min_value'] = forsdata.min(axis=1)

In [180]:
forsdata[forsdata['consistency']==1]

,[[EWB1] I have a clear set of goals and aims to enable me to do my job],[[EWB2] I feel able to voice opinions and influence changes in my area of work],[[EWB3] I have the opportunity to use my abilities at work],[[EWB4] I feel well at the moment],[[EWB5] My employer provides adequate facilities and flexibility for me to fit work in around my family life],[[EWB6] My current working hours / patterns suit my personal circumstances],[[EWB7] I often feel under pressure at work],[[EWB8] When I have done a good job it is acknowledged by my line manager],"[[EWB9] Recently, I have been feeling unhappy and depressed]",[[EWB10] I am satisfied with my life],...,[[OP11] Employees are permitted enough discretion in doing their work],[[OP12] Employees are encouraged to raise their voice when they disagree over a decision],[[OP13] The organization provides enough opportunity to employees for providing inputs on a wide range of issues],[[OP14] Employees are involved in decision making with regard to recruitment and selection of a new colleague],Employment Sector,Education Level,Monthly Income,max_value,min_value,consistency
5,4,4,4,4,4.0,4,4,4,4,4,...,4,4.0,4.0,4.0,Private-sector based,Bachelor Degree,"Above RM11,819",4.0,4.0,1.0
6,4,4,4,4,4.0,4,4,4,4,4,...,4,4.0,4.0,4.0,Private-sector based,Bachelor Degree,"Above RM11,819",4.0,4.0,1.0
7,4,4,4,4,4.0,4,4,4,4,4,...,4,4.0,4.0,4.0,Private-sector based,Secondary School,"Above RM11,819",4.0,4.0,1.0
48,4,4,4,4,4.0,4,4,4,4,4,...,4,4.0,4.0,4.0,Government-sector based,Bachelor Degree,"Below RM3,440",4.0,4.0,1.0
51,5,5,5,5,5.0,5,5,5,5,5,...,5,5.0,5.0,5.0,Government-sector based,Master,"Below RM3,440",5.0,5.0,1.0
98,4,4,4,4,4.0,4,4,4,4,4,...,4,4.0,4.0,4.0,Private-sector based,Bachelor Degree,"RM3,440 - RM5,249",4.0,4.0,1.0
116,3,3,3,3,3.0,3,3,3,3,3,...,3,3.0,3.0,3.0,Private-sector based,Secondary School,"Below RM3,440",3.0,3.0,1.0

In [181]:
import random
import pandas as pd
from fancyimpute import IterativeImputer

# Assuming you have already loaded your dataframe 'genx'

# Select relevant columns
# forsdata = genx.iloc[:, [i for i in range(0, len(genx.columns)) if i in [70, 71, 72]]]

# Randomly select values for 'Employment Sector', 'Education Level', and 'Monthly Income'
sector = random.choice(forsdata['Employment Sector'].unique())
education = random.choice(forsdata['Education Level'].unique())
income = random.choice(forsdata['Monthly Income'].unique())

# Fill the selected values in the dataframe
forsdata.loc[forsdata['Employment Sector'].isnull(), 'Employment Sector'] = sector
forsdata.loc[forsdata['Education Level'].isnull(), 'Education Level'] = education
forsdata.loc[forsdata['Monthly Income'].isnull(), 'Monthly Income'] = income

# Now, let's use MICE to impute missing values in other columns
exclude_columns = ['Employment Sector', 'Education Level', 'Monthly Income']

# Specify columns to impute
columns_to_impute = [col for col in forsdata.columns if col not in exclude_columns]

# Create imputer 
imputer = IterativeImputer()

# Fit and transform to impute 
forsdata_imputed = pd.DataFrame(imputer.fit_transform(forsdata[columns_to_impute]), 
                               columns=columns_to_impute)  

# Replace imputed values
forsdata[columns_to_impute] = forsdata_imputed[columns_to_impute]

# Generate 100 synthetic data points
synthetic_data = pd.DataFrame(columns=forsdata.columns)
for _ in range(100):
    synthetic_row = forsdata.iloc[random.randint(0, len(forsdata) - 1)]
    synthetic_data = synthetic_data.append(synthetic_row, ignore_index=True)

# Convert numeric columns to integers
synthetic_data[columns_to_impute] = synthetic_data[columns_to_impute].astype(int)

# Display the synthetic data
synthetic_data

C:\Users\najmi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\impute\_iterative.py:785: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
C:\Users\najmi\AppData\Local\Temp\ipykernel_23788\435860509.py:40: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  synthetic_data = synthetic_data.append(synthetic_row, ignore_index=True)

,[[EWB1] I have a clear set of goals and aims to enable me to do my job],[[EWB2] I feel able to voice opinions and influence changes in my area of work],[[EWB3] I have the opportunity to use my abilities at work],[[EWB4] I feel well at the moment],[[EWB5] My employer provides adequate facilities and flexibility for me to fit work in around my family life],[[EWB6] My current working hours / patterns suit my personal circumstances],[[EWB7] I often feel under pressure at work],[[EWB8] When I have done a good job it is acknowledged by my line manager],"[[EWB9] Recently, I have been feeling unhappy and depressed]",[[EWB10] I am satisfied with my life],...,[[OP11] Employees are permitted enough discretion in doing their work],[[OP12] Employees are encouraged to raise their voice when they disagree over a decision],[[OP13] The organization provides enough opportunity to employees for providing inputs on a wide range of issues],[[OP14] Employees are involved in decision making with regard to recruitment and selection of a new colleague],Employment Sector,Education Level,Monthly Income,max_value,min_value,consistency
0,5,5,5,5,4,5,5,5,5,2,...,3,4,4,4,Private-sector based,Bachelor Degree,"Below RM3,440",5,2,2
1,4,4,5,5,3,1,4,5,3,5,...,4,4,5,4,Government-sector based,Bachelor Degree,"RM3,440 - RM5,249",5,1,5
2,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,Private-sector based,Bachelor Degree,"RM3,440 - RM5,249",4,4,1
3,4,4,4,4,5,5,2,4,2,4,...,5,3,4,4,Others,Bachelor Degree,"Below RM3,440",5,1,5
4,3,3,4,4,3,4,4,3,3,2,...,4,4,4,4,Others,Bachelor Degree,"Below RM3,440",5,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,5,4,4,3,4,5,2,5,4,2,...,5,5,5,5,Private-sector based,Bachelor Degree,"RM3,440 - RM5,249",5,2,2
96,4,2,4,4,2,2,4,2,2,4,...,4,4,4,2,Private-sector based,Master,"RM3,440 - RM5,249",4,2,2
97,3,4,4,4,4,3,3,4,3,3,...,4,3,3,3,Private-sector based,Bachelor Degree,"Below RM3,440",4,3,1
98,5,5,5,5,4,5,5,5,5,2,...,3,4,4,4,Private-sector based,Bachelor Degree,"Below RM3,440",5,2,2
99,2,3,3,3,4,3,3,3,3,3,...,4,3,2,3,Private-sector based,Master,"Below RM3,440",4,2,2

In [182]:
synthetic_data.to_csv('synthetic_data_genZ.csv', index=False)

In [183]:
synthetic_data.to_clipboard(index=False)